### ISSUE TITLE
Building for WebGL ?

### ISSUE THREAD

**Issue by 99bits** [luiseduve/exciteometer#13]
Thanks for your help Luis,

I'm now trying to build the project for webgl and getting these errors.  Have you tried it for Webgl?  I'm testing the project without LSL.  Just with the synthetic data.

![image](https://user-images.githubusercontent.com/22409112/230724425-23eb0bf2-3e28-4a85-abed-b4815edf082c.png)

RuntimeError: null function or function signature mismatch,RuntimeError: null function or function signature mismatch
    at wasm://wasm/05df438e:wasm-function[63118]:0x10ec56f
    at wasm://wasm/05df438e:wasm-function[39276]:0xb81ace
    at invoke_vii (http://localhost/test_ble/Build/BLE%20exciteometer%20web.framework.js:3:370955)
    at wasm://wasm/05df438e:wasm-function[63296]:0x10f560c
    at wasm://wasm/05df438e:wasm-function[52350]:0xf68e4f
    at wasm://wasm/05df438e:wasm-function[9166]:0x2f34bd
    at wasm://wasm/05df438e:wasm-function[39273]:0xb81a5e
    at invoke_iiii (http://localhost/test_ble/Build/BLE%20exciteometer%20web.framework.js:3:369932)
    at wasm://wasm/05df438e:wasm-function[1597]:0xa018c
    at wasm://wasm/05df438e:wasm-function[35769]:0xb0a5c8
    at wasm://wasm/05df438e:wasm-function[22208]:0x8bf58e
    at wasm://wasm/05df438e:wasm-function[9313]:0x2f687e
    at wasm://wasm/05df438e:wasm-function[13207]:0x4b3d4b
    at wasm://wasm/05df438e:wasm-function[19086]:0x65858f
    at wasm://wasm/05df438e:wasm-function[43531]:0xc98d3c
    at wasm://wasm/05df438e:wasm-function[19083]:0x657ba9
    at wasm://wasm/05df438e:wasm-function[19082]:0x657903
    at wasm://wasm/05df438e:wasm-function[8425]:0x27c159
    at wasm://wasm/05df438e:wasm-function[39286]:0xb9d4c1
    at Module._main (http://localhost/test_ble/Build/BLE%20exciteometer%20web.framework.js:3:301181)
    at callMain (http://localhost/test_ble/Build/BLE%20exciteometer%20web.framework.js:3:385681)
    at doRun (http://localhost/test_ble/Build/BLE%20exciteometer%20web.framework.js:3:386241)
    at run (http://localhost/test_ble/Build/BLE%20exciteometer%20web.framework.js:3:386413)
    at runCaller (http://localhost/test_ble/Build/BLE%20exciteometer%20web.framework.js:3:385340)
    at Object.removeRunDependency (http://localhost/test_ble/Build/BLE%20exciteometer%20web.framework.js:3:16322)
    at http://localhost/test_ble/Build/BLE%20exciteometer%20web.framework.js:3:1948
    at doCallback (http://localhost/test_ble/Build/BLE%20exciteometer%20web.framework.js:3:93440)
    at done (http://localhost/test_ble/Build/BLE%20exciteometer%20web.framework.js:3:93594)
    at transaction.oncomplete (http://localhost/test_ble/Build/BLE%20exciteometer%20web.framework.js:3:86699)
printErr @ BLE exciteometer web.loader.js:1
callMain @ BLE exciteometer web.framework.js:3
doRun @ BLE exciteometer web.framework.js:3
run @ BLE exciteometer web.framework.js:3
runCaller @ BLE exciteometer web.framework.js:3
removeRunDependency @ BLE exciteometer web.framework.js:3
(anonymous) @ BLE exciteometer web.framework.js:3
doCallback @ BLE exciteometer web.framework.js:3
done @ BLE exciteometer web.framework.js:3
transaction.oncomplete @ BLE exciteometer web.framework.js:3
BLE exciteometer web.framework.js:3 Uncaught RuntimeError: null function or function signature mismatch
    at 05df438e:0x10ec56f
    at 05df438e:0xb81ace
    at invoke_vii (BLE exciteometer web.framework.js:3:370955)
    at 05df438e:0x10f560c
    at 05df438e:0xf68e4f
    at 05df438e:0x2f34bd
    at 05df438e:0xb81a5e
    at invoke_iiii (BLE exciteometer web.framework.js:3:369932)
    at 05df438e:0xa018c
    at 05df438e:0xb0a5c8
    at 05df438e:0x8bf58e
    at 05df438e:0x2f687e
    at 05df438e:0x4b3d4b
    at 05df438e:0x65858f
    at 05df438e:0xc98d3c
    at 05df438e:0x657ba9
    at 05df438e:0x657903
    at 05df438e:0x27c159
    at 05df438e:0xb9d4c1
    at Module._main (BLE exciteometer web.framework.js:3:301181)
    at callMain (BLE exciteometer web.framework.js:3:385681)
    at doRun (BLE exciteometer web.framework.js:3:386241)
    at run (BLE exciteometer web.framework.js:3:386413)
    at runCaller (BLE exciteometer web.framework.js:3:385340)
    at Object.removeRunDependency (BLE exciteometer web.framework.js:3:16322)
    at BLE exciteometer web.framework.js:3:1948
    at doCallback (BLE exciteometer web.framework.js:3:93440)
    at done (BLE exciteometer web.framework.js:3:93594)
    at transaction.oncomplete (BLE exciteometer web.framework.js:3:86699)

**Comment by 99bits** [comment]
Question:  Can you give some hints as to what the app is doing in terms of accessing the native file system, writing files, etc.  Things that would not be feasible on a webgl platform.

**Comment by luisqtr** [comment]
Hi,
Never tried WebGL and not very experienced on web-related things, so I don't know what the problem might be. Let me know in case you manage to build for webgl to include it in the main repo.

Everything about the file system is organized in the file `EoM\Module1_DataProcessing\Scripts\DataLogger\LoggerController.cs`
